
zOPCODE__LBLS_L: .BYTE 256
zOPCODE__LBLS_H: .BYTE 256
zOPCODE_CB_LBLS_L: .BYTE 256
zOPCODE_CB_LBLS_H: .BYTE 256
zOPCODE_DD_LBLS_L: .BYTE 256
zOPCODE_DD_LBLS_H: .BYTE 256
zOPCODE_ED_LBLS_L: .BYTE 256
zOPCODE_ED_LBLS_H: .BYTE 256
zOPCODE_FD_LBLS_L: .BYTE 256
zOPCODE_FD_LBLS_H: .BYTE 256
zOPCODE_DDCB_LBLS_L: .BYTE 256
zOPCODE_DDCB_LBLS_H: .BYTE 256
zOPCODE_FDCB_LBLS_L: .BYTE 256
zOPCODE_FDCB_LBLS_H: .BYTE 256