
S1a:	ld	itemp, X+
S1b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S2a
	nop
	rjmp	S2b

S2a:	ld	itemp, X+
S2b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S3a
	nop
	rjmp	S3b

S3a:	ld	itemp, X+
S3b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S4a
	nop
	rjmp	S4b

S4a:	ld	itemp, X+
S4b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S5a
	nop
	rjmp	S5b

S5a:	ld	itemp, X+
S5b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S6a
	nop     
	rjmp	S6b

S6a:	ld	itemp, X+
S6b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S7a
	nop
	rjmp	S7b

S7a:	ld	itemp, X+
S7b:	subi	itemp, 8
	out		PORTA, itemp
	brpl	S8a
	nop
	rjmp	S8b

S8a:	ld	itemp, X+
S8b:	subi	itemp, 8
	out		PORTA, itemp
	brpl	S9a
	nop
	rjmp	S9b

S9a:	ld	itemp, X+
S9b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S10a
	nop
	rjmp	S10b

S10a:	ld	itemp, X+
S10b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S11a
	nop
	rjmp	S11b

S11a:	ld	itemp, X+
S11b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S12a
	nop
	rjmp	S12b

S12a:	ld	itemp, X+
S12b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S13a
	nop
	rjmp	S13b

S13a:	ld	itemp, X+
S13b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S14a
	nop
	rjmp	S14b

S14a:	ld	itemp, X+
S14b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S15a
	nop
	rjmp	S15b

S15a:	ld	itemp, X+
S15b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S16a
	nop
	rjmp	S16b

S16a:	ld	itemp, X+
S16b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S17a
	nop
	rjmp	S17b

S17a:	ld	itemp, X+
S17b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S18a
	nop
	rjmp	S18b

S18a:	ld	itemp, X+
S18b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S19a
	nop
	rjmp	S19b

S19a:	ld	itemp, X+
S19b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S20a
	nop
	rjmp	S20b

S20a:	ld	itemp, X+
S20b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S21a
	nop
	rjmp	S21b

S21a:	ld	itemp, X+
S21b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S22a
	nop
	rjmp	S22b

S22a:	ld	itemp, X+
S22b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S23a
	nop
	rjmp	S23b

S23a:	ld	itemp, X+
S23b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S24a
	nop
	rjmp	S24b

S24a:	ld	itemp, X+
S24b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S25a
	nop
	rjmp	S25b

S25a:	ld	itemp, X+
S25b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S26a
	nop
	rjmp	S26b

S26a:	ld	itemp, X+
S26b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S27a
	nop
	rjmp	S27b

S27a:	ld	itemp, X+
S27b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S28a
	nop
	rjmp	S28b

S28a:	ld	itemp, X+
S28b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S29a
	nop
	rjmp	S29b

S29a:	ld	itemp, X+
S29b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S30a
	nop
	rjmp	S30b

S30a:	ld	itemp, X+
S30b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S31a
	nop
	rjmp	S31b

S31a:	ld	itemp, X+
S31b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S32a
	nop
	rjmp	S32b

S32a:	ld	itemp, X+
S32b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	S33a
	nop
	rjmp	S33b


S33a:	ld	itemp, X+
S33b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	S34a
	nop
	rjmp	S34b

s34a:	ld	itemp, X+
s34b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s35a
	nop
	rjmp	s35b

s35a:	ld	itemp, X+
s35b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s36a
	nop
	rjmp	s36b

s36a:	ld	itemp, X+
s36b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s37a
	nop
	rjmp	s37b

s37a:	ld	itemp, X+
s37b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s38a
	nop
	rjmp	s38b

s38a:	ld	itemp, X+
s38b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s39a
	nop
	rjmp	s39b

s39a:	ld	itemp, X+
s39b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s40a
	nop
	rjmp	s40b


s40a:	ld	itemp, X+
s40b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s41a
	nop
	rjmp	s41b

s41a:	ld	itemp, X+
s41b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s42a
	nop
	rjmp	s42b

s42a:	ld	itemp, X+
s42b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s43a
	nop
	rjmp	s43b


s43a:	ld	itemp, X+
s43b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s44a
	nop
	rjmp	s44b

s44a:	ld	itemp, X+
s44b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s45a
	nop
	rjmp	s45b

s45a:	ld	itemp, X+
s45b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s46a
	nop
	rjmp	s46b

s46a:	ld	itemp, X+
s46b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s47a
	nop
	rjmp	s47b

s47a:	ld	itemp, X+
s47b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s48a
	nop
	rjmp	s48b

s48a:	ld	itemp, X+
s48b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s49a
	nop
	rjmp	s49b

s49a:	ld	itemp, X+
s49b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s50a
	nop
	rjmp	s50b


s50a:	ld	itemp, X+
s50b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s51a
	nop
	rjmp	s51b

s51a:	ld	itemp, X+
s51b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s52a
	nop
	rjmp	s52b

s52a:	ld	itemp, X+
s52b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s53a
	nop
	rjmp	s53b


s53a:	ld	itemp, X+
s53b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s54a
	nop
	rjmp	s54b

s54a:	ld	itemp, X+
s54b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s55a
	nop
	rjmp	s55b

s55a:	ld	itemp, X+
s55b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s56a
	nop
	rjmp	s56b

s56a:	ld	itemp, X+
s56b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s57a
	nop
	rjmp	s57b

s57a:	ld	itemp, X+
s57b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s58a
	nop
	rjmp	s58b

s58a:	ld	itemp, X+
s58b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s59a
	nop
	rjmp	s59b

s59a:	ld	itemp, X+
s59b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s60a
	nop
	rjmp	s60b

s60a:	ld	itemp, X+
s60b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s61a
	nop
	rjmp	s61b

s61a:	ld	itemp, X+
s61b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s62a
	nop
	rjmp	s62b

s62a:	ld	itemp, X+
s62b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s63a
	nop
	rjmp	s63b


s63a:	ld	itemp, X+
s63b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s64a
	nop
	rjmp	s64b

s64a:	ld	itemp, X+
s64b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s65a
	nop
	rjmp	s65b

s65a:	ld	itemp, X+
s65b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s66a
	nop
	rjmp	s66b

s66a:	ld	itemp, X+
s66b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s67a
	nop
	rjmp	s67b

s67a:	ld	itemp, X+
s67b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s68a
	nop
	rjmp	s68b

s68a:	ld	itemp, X+
s68b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s69a
	nop
	rjmp	s69b

s69a:	ld	itemp, X+
s69b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s70a
	nop
	rjmp	s70b

s70a:	ld	itemp, X+
s70b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s71a
	nop
	rjmp	s71b

s71a:	ld	itemp, X+
s71b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s72a
	nop
	rjmp	s72b

s72a:	ld	itemp, X+
s72b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s73a
	nop
	rjmp	s73b

s73a:	ld	itemp, X+
s73b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s74a
	nop
	rjmp	s74b

s74a:	ld	itemp, X+
s74b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s75a
	nop
	rjmp	s75b

s75a:	ld	itemp, X+
s75b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s76a
	nop
	rjmp	s76b

s76a:	ld	itemp, X+
s76b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s77a
	nop
	rjmp	s77b

s77a:	ld	itemp, X+
s77b:	subi	itemp, 8
	out	PORTA, itemp
	nop	;!!! NOP !!!
	brpl	s78a
	nop
	rjmp	s78b

s78a:	ld	itemp, X+
s78b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s79a
	nop
	rjmp	s79b

s79a:	ld	itemp, X+
s79b:	subi	itemp, 8
	out	PORTA, itemp
	brpl	s80a
	nop
	rjmp	s80b

s80a:	ld	itemp, X+
s80b:	subi	itemp, 8
	out	PORTA, itemp
;	nop	;!!! NOP !!!
	brpl	s81a
	nop
	rjmp	s81b

S81a:	nop
S81b:	nop
